# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0
# This kustomization.yaml is not intended to be runtime by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be runtime by config/default
resources:
- bases/goharbor.goharbor.io_inspectionpolicies.yaml
- bases/goharbor.goharbor.io_inspections.yaml
- bases/goharbor.goharbor.io_assessmentreports.yaml
- bases/goharbor.goharbor.io_settings.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_inspectionpolicies.yaml
#- patches/webhook_in_inspections.yaml
#- patches/webhook_in_assessmentreports.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_inspectionpolicies.yaml
#- patches/cainjection_in_inspections.yaml
#- patches/cainjection_in_assessmentreports.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
